---
driver:
  name: vagrant
  provider: virtualbox
  gui: true
  username: vagrant
  password: vagrant
  elevated: true
  elevated_username: vagrant
  elevated_password: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[eclipse::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
